repos:
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint-plugin-react@6.10.3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.781
    hooks:
    -   id: mypy
