version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  backend:
    build: ./api/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      args:
        API_URL: http://backend:8000
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
