version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      context: ./backend
      args:
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static/:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://backend:3000
    command: ["npm", "start"]
    volumes:
      - build_folder:/frontend/build
      - node-modules:/frontend/frontend/node_modules
    ports:
      - "3000:3000"
volumes:
  build_folder:
