# Generated by Django 3.2.5 on 2021-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_manhwa_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwa",
            name="tags",
            field=models.ManyToManyField(blank=True, to="web.Tags"),
        ),
    ]
