# Generated by Django 3.2.6 on 2021-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_manhwalist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwalist",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
