# Generated by Django 3.2.6 on 2021-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_manhwalist_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwalist",
            name="manhwas",
            field=models.ManyToManyField(blank=True, to="web.Manhwa"),
        ),
    ]
