# Generated by Django 3.2.5 on 2021-07-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_auto_20210730_1800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwa",
            name="cover_image",
            field=models.ImageField(upload_to="media/images/cover_images"),
        ),
    ]
