# Generated by Django 3.2.5 on 2021-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_manhwa_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwa",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ongoing", "Ongoing"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                max_length=255,
            ),
        ),
    ]
