# Generated by Django 3.2.5 on 2021-08-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_manhwa_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwa",
            name="author",
            field=models.CharField(max_length=255),
        ),
    ]
