# Generated by Django 3.2.5 on 2021-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_manhwa_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManhwaList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("identifier", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("manhwas", models.ManyToManyField(to="web.Manhwa")),
            ],
        ),
    ]
