# Generated by Django 3.2.6 on 2021-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_manhwalist_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwa",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="web.Tags"),
        ),
    ]
