# Generated by Django 3.2.6 on 2021-12-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_alter_manhwa_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="type",
            field=models.CharField(
                choices=[("Manhwa", "Manhwa"), ("Manhua", "Manhua")],
                default="Manhwa",
                max_length=255,
            ),
        ),
    ]
