# Generated by Django 3.2.6 on 2022-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_alter_manhwalist_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manhwa",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("Verified", "Verified"),
                    ("Unverified", "Unverified"),
                    ("Rejected", "Rejected"),
                ],
                default="Unverified",
                max_length=255,
            ),
        ),
    ]
