# Generated by Django 3.2.6 on 2022-01-08 16:47

from django.db import migrations


def update_verification_status(apps, schema_editor):
    Manhwa = apps.get_model("web", "Manhwa")
    for manhwa in Manhwa.objects.all():
        if manhwa.verified:
            manhwa.verification_status = "Verified"
        else:
            manhwa.verification_status = "Unverified"
        manhwa.save()


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_auto_20220108_1647"),
    ]

    operations = [
        migrations.RunPython(update_verification_status),
    ]
