# Generated by Django 3.2.6 on 2022-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_auto_20220108_1647"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwa",
            name="alternate_names",
            field=models.CharField(
                blank=True,
                help_text="Add comma separated values for the alternate names for the manhwa",
                max_length=750,
                null=True,
            ),
        ),
    ]
